// Code generated by Mir codegen. DO NOT EDIT.

package bcpbmsgs

import (
	types1 "github.com/filecoin-project/mir/pkg/pb/aleapb/bcpb/types"
	types2 "github.com/filecoin-project/mir/pkg/pb/messagepb/types"
	types3 "github.com/filecoin-project/mir/pkg/pb/trantorpb/types"
	types "github.com/filecoin-project/mir/pkg/types"
)

func FillGapMessage(destModule types.ModuleID, slot *types1.Slot) *types2.Message {
	return &types2.Message{
		DestModule: destModule,
		Type: &types2.Message_AleaBroadcast{
			AleaBroadcast: &types1.Message{
				Type: &types1.Message_FillGapMessage{
					FillGapMessage: &types1.FillGapMessage{
						Slot: slot,
					},
				},
			},
		},
	}
}

func FillerMessage(destModule types.ModuleID, cert *types1.Cert, txs []*types3.Transaction) *types2.Message {
	return &types2.Message{
		DestModule: destModule,
		Type: &types2.Message_AleaBroadcast{
			AleaBroadcast: &types1.Message{
				Type: &types1.Message_FillerMessage{
					FillerMessage: &types1.FillerMessage{
						Cert: cert,
						Txs:  txs,
					},
				},
			},
		},
	}
}
