linters:
  enable:
    - asciicheck
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - gocognit
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/filecoin-project/mir
  gocognit:
    min-complexity: 50

run:
  timeout: 5m
  skip-dirs:
    - pkg/pb # Skip generated files

issues:
  exclude-rules:
    - path: .*\.mir\.go
      linters: [revive, stylecheck, goimports, gocyclo]

    # SA1019 is applicable to aggregate signatures (which are not used here), not threshold signatures 
    - path: pkg/threshcrypto/tbls.go
      linters: [staticcheck]
      text: SA1019
