// Code generated by Mir codegen. DO NOT EDIT.

package agreementpb

import (
	reflect "reflect"
)

func (*Message) ReflectTypeOptions() []reflect.Type {
	return []reflect.Type{
		reflect.TypeOf((*Message_FinishAbba)(nil)),
	}
}
