// Code generated by Mir codegen. DO NOT EDIT.

package directorpbmsgs

import (
	types3 "github.com/filecoin-project/mir/pkg/pb/aleapb/directorpb/types"
	types2 "github.com/filecoin-project/mir/pkg/pb/messagepb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/threshcheckpointpb/types"
	types "github.com/filecoin-project/mir/pkg/types"
)

func StableCheckpoint(destModule types.ModuleID, checkpoint *types1.StableCheckpoint) *types2.Message {
	return &types2.Message{
		DestModule: destModule,
		Type: &types2.Message_AleaDirector{
			AleaDirector: &types3.Message{
				Type: &types3.Message_StableCheckpoint{
					StableCheckpoint: &types3.StableCheckpoint{
						Checkpoint: checkpoint,
					},
				},
			},
		},
	}
}
