// Code generated by Mir codegen. DO NOT EDIT.

package agevents

import (
	reflect "reflect"
)

func (*Event) ReflectTypeOptions() []reflect.Type {
	return []reflect.Type{
		reflect.TypeOf((*Event_InputValue)(nil)),
		reflect.TypeOf((*Event_Deliver)(nil)),
		reflect.TypeOf((*Event_StaleMsgsRevcd)(nil)),
		reflect.TypeOf((*Event_InnerAbbaRoundTime)(nil)),
	}
}
