// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: reliablenetpb/reliablenetpb.proto

package reliablenetpb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	messagepb "github.com/filecoin-project/mir/pkg/pb/messagepb"
	_ "github.com/filecoin-project/mir/pkg/pb/mir"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*Event_SendMessage
	//	*Event_Ack
	//	*Event_MarkRecvd
	//	*Event_MarkModuleMsgsRecvd
	//	*Event_RetransmitAll
	Type isEvent_Type `protobuf_oneof:"type"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reliablenetpb_reliablenetpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_reliablenetpb_reliablenetpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_reliablenetpb_reliablenetpb_proto_rawDescGZIP(), []int{0}
}

func (m *Event) GetType() isEvent_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Event) GetSendMessage() *SendMessage {
	if x, ok := x.GetType().(*Event_SendMessage); ok {
		return x.SendMessage
	}
	return nil
}

func (x *Event) GetAck() *Ack {
	if x, ok := x.GetType().(*Event_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *Event) GetMarkRecvd() *MarkRecvd {
	if x, ok := x.GetType().(*Event_MarkRecvd); ok {
		return x.MarkRecvd
	}
	return nil
}

func (x *Event) GetMarkModuleMsgsRecvd() *MarkModuleMsgsRecvd {
	if x, ok := x.GetType().(*Event_MarkModuleMsgsRecvd); ok {
		return x.MarkModuleMsgsRecvd
	}
	return nil
}

func (x *Event) GetRetransmitAll() *RetransmitAll {
	if x, ok := x.GetType().(*Event_RetransmitAll); ok {
		return x.RetransmitAll
	}
	return nil
}

type isEvent_Type interface {
	isEvent_Type()
}

type Event_SendMessage struct {
	SendMessage *SendMessage `protobuf:"bytes,1,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type Event_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type Event_MarkRecvd struct {
	MarkRecvd *MarkRecvd `protobuf:"bytes,3,opt,name=mark_recvd,json=markRecvd,proto3,oneof"`
}

type Event_MarkModuleMsgsRecvd struct {
	MarkModuleMsgsRecvd *MarkModuleMsgsRecvd `protobuf:"bytes,4,opt,name=mark_module_msgs_recvd,json=markModuleMsgsRecvd,proto3,oneof"`
}

type Event_RetransmitAll struct {
	RetransmitAll *RetransmitAll `protobuf:"bytes,5,opt,name=retransmit_all,json=retransmitAll,proto3,oneof"`
}

func (*Event_SendMessage) isEvent_Type() {}

func (*Event_Ack) isEvent_Type() {}

func (*Event_MarkRecvd) isEvent_Type() {}

func (*Event_MarkModuleMsgsRecvd) isEvent_Type() {}

func (*Event_RetransmitAll) isEvent_Type() {}

type SendMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg          *messagepb.Message `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Destinations []string           `protobuf:"bytes,2,rep,name=destinations,proto3" json:"destinations,omitempty"`
	MsgId        []byte             `protobuf:"bytes,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reliablenetpb_reliablenetpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_reliablenetpb_reliablenetpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_reliablenetpb_reliablenetpb_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessage) GetMsg() *messagepb.Message {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SendMessage) GetDestinations() []string {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *SendMessage) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DestModule string `protobuf:"bytes,1,opt,name=dest_module,json=destModule,proto3" json:"dest_module,omitempty"`
	MsgId      []byte `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Source     string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reliablenetpb_reliablenetpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_reliablenetpb_reliablenetpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_reliablenetpb_reliablenetpb_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetDestModule() string {
	if x != nil {
		return x.DestModule
	}
	return ""
}

func (x *Ack) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *Ack) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type MarkModuleMsgsRecvd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DestModule   string   `protobuf:"bytes,1,opt,name=dest_module,json=destModule,proto3" json:"dest_module,omitempty"`
	Destinations []string `protobuf:"bytes,2,rep,name=destinations,proto3" json:"destinations,omitempty"`
}

func (x *MarkModuleMsgsRecvd) Reset() {
	*x = MarkModuleMsgsRecvd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reliablenetpb_reliablenetpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkModuleMsgsRecvd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkModuleMsgsRecvd) ProtoMessage() {}

func (x *MarkModuleMsgsRecvd) ProtoReflect() protoreflect.Message {
	mi := &file_reliablenetpb_reliablenetpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkModuleMsgsRecvd.ProtoReflect.Descriptor instead.
func (*MarkModuleMsgsRecvd) Descriptor() ([]byte, []int) {
	return file_reliablenetpb_reliablenetpb_proto_rawDescGZIP(), []int{3}
}

func (x *MarkModuleMsgsRecvd) GetDestModule() string {
	if x != nil {
		return x.DestModule
	}
	return ""
}

func (x *MarkModuleMsgsRecvd) GetDestinations() []string {
	if x != nil {
		return x.Destinations
	}
	return nil
}

type MarkRecvd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DestModule   string   `protobuf:"bytes,1,opt,name=dest_module,json=destModule,proto3" json:"dest_module,omitempty"`
	MsgId        []byte   `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Destinations []string `protobuf:"bytes,3,rep,name=destinations,proto3" json:"destinations,omitempty"`
}

func (x *MarkRecvd) Reset() {
	*x = MarkRecvd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reliablenetpb_reliablenetpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkRecvd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRecvd) ProtoMessage() {}

func (x *MarkRecvd) ProtoReflect() protoreflect.Message {
	mi := &file_reliablenetpb_reliablenetpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRecvd.ProtoReflect.Descriptor instead.
func (*MarkRecvd) Descriptor() ([]byte, []int) {
	return file_reliablenetpb_reliablenetpb_proto_rawDescGZIP(), []int{4}
}

func (x *MarkRecvd) GetDestModule() string {
	if x != nil {
		return x.DestModule
	}
	return ""
}

func (x *MarkRecvd) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *MarkRecvd) GetDestinations() []string {
	if x != nil {
		return x.Destinations
	}
	return nil
}

type RetransmitAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetransmitAll) Reset() {
	*x = RetransmitAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reliablenetpb_reliablenetpb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetransmitAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetransmitAll) ProtoMessage() {}

func (x *RetransmitAll) ProtoReflect() protoreflect.Message {
	mi := &file_reliablenetpb_reliablenetpb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetransmitAll.ProtoReflect.Descriptor instead.
func (*RetransmitAll) Descriptor() ([]byte, []int) {
	return file_reliablenetpb_reliablenetpb_proto_rawDescGZIP(), []int{5}
}

var File_reliablenetpb_reliablenetpb_proto protoreflect.FileDescriptor

var file_reliablenetpb_reliablenetpb_proto_rawDesc = []byte{
	0x0a, 0x21, 0x72, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x6e, 0x65, 0x74, 0x70, 0x62, 0x2f,
	0x72, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x6e, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x72, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x6e, 0x65, 0x74,
	0x70, 0x62, 0x1a, 0x19, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x70, 0x62, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x6d,
	0x69, 0x72, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xdb, 0x02, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x0c, 0x73, 0x65, 0x6e,
	0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x72, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x6e, 0x65, 0x74, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x73,
	0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x61, 0x63,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x6c, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x6e, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x03, 0x61,
	0x63, 0x6b, 0x12, 0x39, 0x0a, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x5f, 0x72, 0x65, 0x63, 0x76, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x6e, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x63, 0x76, 0x64,
	0x48, 0x00, 0x52, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x63, 0x76, 0x64, 0x12, 0x59, 0x0a,
	0x16, 0x6d, 0x61, 0x72, 0x6b, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x6d, 0x73, 0x67,
	0x73, 0x5f, 0x72, 0x65, 0x63, 0x76, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x72, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x6e, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x4d, 0x61,
	0x72, 0x6b, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4d, 0x73, 0x67, 0x73, 0x52, 0x65, 0x63, 0x76,
	0x64, 0x48, 0x00, 0x52, 0x13, 0x6d, 0x61, 0x72, 0x6b, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4d,
	0x73, 0x67, 0x73, 0x52, 0x65, 0x63, 0x76, 0x64, 0x12, 0x45, 0x0a, 0x0e, 0x72, 0x65, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x72, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x6e, 0x65, 0x74, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x00,
	0x52, 0x0d, 0x72, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x41, 0x6c, 0x6c, 0x42,
	0x0c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x04, 0x80, 0xb5, 0x18, 0x01, 0x22, 0x6e, 0x0a,
	0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x55, 0x0a,
	0x03, 0x41, 0x63, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x73, 0x74, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x22, 0x5a, 0x0a, 0x13, 0x4d, 0x61, 0x72, 0x6b, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x4d, 0x73, 0x67, 0x73, 0x52, 0x65, 0x63, 0x76, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x64, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x67, 0x0a, 0x09, 0x4d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x63, 0x76, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x15,
	0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x63, 0x6f, 0x69,
	0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6d, 0x69, 0x72, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x6e, 0x65, 0x74,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reliablenetpb_reliablenetpb_proto_rawDescOnce sync.Once
	file_reliablenetpb_reliablenetpb_proto_rawDescData = file_reliablenetpb_reliablenetpb_proto_rawDesc
)

func file_reliablenetpb_reliablenetpb_proto_rawDescGZIP() []byte {
	file_reliablenetpb_reliablenetpb_proto_rawDescOnce.Do(func() {
		file_reliablenetpb_reliablenetpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_reliablenetpb_reliablenetpb_proto_rawDescData)
	})
	return file_reliablenetpb_reliablenetpb_proto_rawDescData
}

var file_reliablenetpb_reliablenetpb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_reliablenetpb_reliablenetpb_proto_goTypes = []interface{}{
	(*Event)(nil),               // 0: reliablenetpb.Event
	(*SendMessage)(nil),         // 1: reliablenetpb.SendMessage
	(*Ack)(nil),                 // 2: reliablenetpb.Ack
	(*MarkModuleMsgsRecvd)(nil), // 3: reliablenetpb.MarkModuleMsgsRecvd
	(*MarkRecvd)(nil),           // 4: reliablenetpb.MarkRecvd
	(*RetransmitAll)(nil),       // 5: reliablenetpb.RetransmitAll
	(*messagepb.Message)(nil),   // 6: messagepb.Message
}
var file_reliablenetpb_reliablenetpb_proto_depIdxs = []int32{
	1, // 0: reliablenetpb.Event.send_message:type_name -> reliablenetpb.SendMessage
	2, // 1: reliablenetpb.Event.ack:type_name -> reliablenetpb.Ack
	4, // 2: reliablenetpb.Event.mark_recvd:type_name -> reliablenetpb.MarkRecvd
	3, // 3: reliablenetpb.Event.mark_module_msgs_recvd:type_name -> reliablenetpb.MarkModuleMsgsRecvd
	5, // 4: reliablenetpb.Event.retransmit_all:type_name -> reliablenetpb.RetransmitAll
	6, // 5: reliablenetpb.SendMessage.msg:type_name -> messagepb.Message
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_reliablenetpb_reliablenetpb_proto_init() }
func file_reliablenetpb_reliablenetpb_proto_init() {
	if File_reliablenetpb_reliablenetpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reliablenetpb_reliablenetpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reliablenetpb_reliablenetpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reliablenetpb_reliablenetpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reliablenetpb_reliablenetpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkModuleMsgsRecvd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reliablenetpb_reliablenetpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkRecvd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reliablenetpb_reliablenetpb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetransmitAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_reliablenetpb_reliablenetpb_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Event_SendMessage)(nil),
		(*Event_Ack)(nil),
		(*Event_MarkRecvd)(nil),
		(*Event_MarkModuleMsgsRecvd)(nil),
		(*Event_RetransmitAll)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reliablenetpb_reliablenetpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reliablenetpb_reliablenetpb_proto_goTypes,
		DependencyIndexes: file_reliablenetpb_reliablenetpb_proto_depIdxs,
		MessageInfos:      file_reliablenetpb_reliablenetpb_proto_msgTypes,
	}.Build()
	File_reliablenetpb_reliablenetpb_proto = out.File
	file_reliablenetpb_reliablenetpb_proto_rawDesc = nil
	file_reliablenetpb_reliablenetpb_proto_goTypes = nil
	file_reliablenetpb_reliablenetpb_proto_depIdxs = nil
}
